# action.yaml
name: "Splunk AppInspect"
description: "Run Splunk App inspect API Calls on Add-on"
inputs:
  username:
    description: username for appinspect authentication
    required: true
  password:
    description: password for appinspect authentication
    required: true
  app_path:
    description: path to addon
    required: true
#    rename to "app_path"
runs:
  using: "docker"
  image: Dockerfile
