# action.yaml
name: "Splunk AppInspect"
description: "Run Splunk App inspect API Calls on Add-on"
runs:
  using: "composite"
  steps:
    - name: 'Make response directory'
      shell: bash
      run: |
        mkdir response
        ls -la
    - name: 'Run Appinspect'
      shell: bash
      run: |
        export ADDON_NAME=$(ls build/package/)
        echo ' --- Addon name is $ADDON_NAME'
        pip install requests
        python main.py "username" "password" "$ADDON_NAME"
inputs:
  username:
    description: username for appinspect authentication
    required: true
  password:
    description: password for appinspect authentication
    required: true